name: Branch test

on:
  push:
    branches-ignore:
      - master
      - development

jobs:
  validation:
    name: "Validate, build and test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate maven wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build test
      - name: Publish test report
        uses: actions/upload-artifact@v2
        with:
          name: \'trade-module\' Test Report
          path: trade-module/build/reports/tests/test/index.html

