name: Branch test

on:
  push:
    branches-ignore:
      - master
      - development

jobs:
  validation:
    name: "Validate, build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/branch-validation-test-steps.yml
